### ISSUE TITLE
Inconsistent GATK entries causing vcfpy.Reader to break

### ISSUE THREAD

**Issue by stolpeo** [bihealth/vcfpy#127]
* vcfpy version: 0.11.0
* Python version: 3.5.4
* Operating System: Ubuntu 16.04 LTS

### Description

I'm trying to read a vcf file that was generated by GATK 3.8. GATK is not annotating according to VCF format specifications. It leaves empty fields in the FORMAT column empty and does not write out separators, e.g.:

```
GT:AD:DP:FT:GQ:PL       ./.:.:.:MinAafHomAlt;MinCovHomAlt;MinGq 
```

### What I Did

The above mentioned line triggers the following error:

```
Traceback (most recent call last):
  File "ped_into_vcf.py", line 136, in <module>
    sys.exit(main())
  File "ped_into_vcf.py", line 132, in main
    run(args)
  File "ped_into_vcf.py", line 116, in run
    extend_vcf(args.vcf_file, pedigree)
  File "ped_into_vcf.py", line 108, in extend_vcf
    writer.write_record(record)
  File "/vol/local/data/miniconda3/lib/python3.5/site-packages/vcfpy/writer.py", line 131, in write_record
    self._serialize_record(record)
  File "/vol/local/data/miniconda3/lib/python3.5/site-packages/vcfpy/writer.py", line 148, in _serialize_record
    for s in self.header.samples.names]
  File "/vol/local/data/miniconda3/lib/python3.5/site-packages/vcfpy/writer.py", line 148, in <listcomp>
    for s in self.header.samples.names]
  File "/vol/local/data/miniconda3/lib/python3.5/site-packages/vcfpy/writer.py", line 170, in _serialize_call
    for key in format_]
  File "/vol/local/data/miniconda3/lib/python3.5/site-packages/vcfpy/writer.py", line 170, in <listcomp>
    for key in format_]
KeyError: 'GQ'
```

**Comment by holtgrewe** [comment]
Resolved in `v0.11.1`.
