### ISSUE TITLE
write_record() error: TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by ok-gitr** [bihealth/vcfpy#143]
* vcfpy version: '0.13.3'
* Python version: 3.8.2
* Operating System: macOS Catalina, Version 10.15.7

Hi, 

I added vcf records from multiple vcfs into a list and when I try to write each record I get the following error:

```
for record in all_records:
    print(record)
    writer.write_record(record)

Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/Users/okcb/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/vcfpy/writer.py", line 130, in write_record
    self._serialize_record(record)
  File "/Users/okcb/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/vcfpy/writer.py", line 144, in _serialize_record
    row.append(f(self._serialize_info(record)))
  File "/Users/okcb/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/vcfpy/writer.py", line 161, in _serialize_info
    result.append("{}={}".format(key, format_value(info, value, "INFO")))
  File "/Users/okcb/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/vcfpy/writer.py", line 48, in format_value
    return ",".join(map(lambda x: format_atomic(x, section), value))
TypeError: 'int' object is not iterable
```

a record in `all_records` looks like this: 
```
Record('1', 2488153, [], 'A', [Substitution(type_='SNV', value='G')], None, ['m2'], {'m2_DP': 1379, 'm2_ECNT': 3, 'm2_POP_AF': [5e-08], 'm2_TLOD': [2137.76]}, ['m2_GT', 'm2_AD', 'm2_AF', 'm2_DP', 'm2_F1R2', 'm2_F2R1', 'm2_MBQ', 'm2_MFRL', 'm2_MMQ', 'm2_MPOS', 'm2_ORIGINAL_CONTIG_MISMATCH', 'm2_SA_MAP_AF', 'm2_SA_POST_PROB'], [Call('20KD-085P0001-1', {'m2_GT': '0/1', 'm2_AD': [672, 656], 'm2_AF': [0.492], 'm2_DP': 1328, 'm2_F1R2': [250, 244], 'm2_F2R1': [422, 412], 'm2_MBQ': [36, 36], 'm2_MFRL': [184, 181], 'm2_MMQ': [60], 'm2_MPOS': [25], 'm2_ORIGINAL_CONTIG_MISMATCH': 0, 'm2_SA_MAP_AF': [0.495, 0.475, 0.494], 'm2_SA_POST_PROB': [0.015, 0.009728, 0.975]})])
```

Any ideas on why this is happening?

Thanks,
O.K

**Comment by holtgrewe** [comment]
Can I see the header? It looks like the `Number` entry of an `INFO` or `GT` field is `1` where it should be of another (or you have to use a `list` somewhere instead of a plain `int`).

**Comment by ok-gitr** [comment]
Thank you, this helped. The problem was indeed with a badly written header.
