### ISSUE TITLE
Couldn't parse compressed vcf file (vcf.bgz)

### ISSUE THREAD

**Issue by SAI-EL** [bihealth/vcfpy#149]
* vcfpy version: 0.13.4
* Python version: 3.10.0
* Operating System: Mac OS

### Description
I was trying to parse a vcf.bgz file but got a UnicodeDecodeError. 

### What I Did
```
vcfpy.Reader.from_path(path)
```

```
Traceback (most recent call last):
  File "/Users/sai/Desktop/Elucidata/scripts/vcf_support/parse_vcfpy.py", line 38, in <module>
    parse_vcf(path)
  File "/Users/sai/Desktop/Elucidata/scripts/vcf_support/parse_vcfpy.py", line 19, in parse_vcf
    vcf_reader = vcfpy.Reader.from_path(path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vcfpy/reader.py", line 94, in from_path
    return klass.from_stream(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vcfpy/reader.py", line 60, in from_stream
    return Reader(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vcfpy/reader.py", line 119, in __init__
    self.parser = parser.Parser(stream, self.path, self.record_checks)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vcfpy/parser.py", line 701, in __init__
    self._line = stream.readline()  # trailing '\n'
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by holtgrewe** [comment]
Hi.

It looks like the issue with with the suffix `.bgzf`.


https://github.com/bihealth/vcfpy/blob/master/vcfpy/reader.py#L86
