### ISSUE TITLE
ModuleNotFoundError: No module named 'pysam'

### ISSUE THREAD

**Issue by Vic-s** [bihealth/vcfpy#150]
* vcfpy version: 0.13.4
* Python version: 3.10.4
* Operating System: Linux (Ubuntu 22.04)

### Description
Try to install and use vcfpy.
Install successful, 
use failed.

I think requirements are not processed correctly when using pip

### What I Did
```
$ pip install vcfpy
Collecting vcfpy
  Downloading vcfpy-0.13.4.tar.gz (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 7.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: vcfpy
  Building wheel for vcfpy (setup.py) ... done
  Created wheel for vcfpy: filename=vcfpy-0.13.4-py2.py3-none-any.whl size=34590 sha256=409354257971197c313d3e7f84b9c8f1e23bda33d78121f4b3efd1662d40488e
  Stored in directory: /home/victor/.cache/pip/wheels/fb/f8/c3/4f2a584f46d0a628bd41c17311e38496eea7b3f8c5ef4309d2
Successfully built vcfpy
Installing collected packages: vcfpy
Successfully installed vcfpy-0.13.4
```

But when using vcfpy
```
$ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcfpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/victor/Documents/python/algemeen/venv/lib/python3.10/site-packages/vcfpy/__init__.py", line 46, in <module>
    from .reader import Reader
  File "/home/victor/Documents/python/algemeen/venv/lib/python3.10/site-packages/vcfpy/reader.py", line 8, in <module>
    import pysam
ModuleNotFoundError: No module named 'pysam'
```

`$ pip list | grep pysam`
does indeed show pysam is not installed.

Checking dependency
`$ python -m pip check`
does not show pysam is missing

In ' base/requirement.txt' 
pysam is mentioned
I think pip is not using it.

Workaround:
manually install pysam
`$ pip install pysam`

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by hylkedonker** [comment]
I can confirm that the problem persists on `vcfpy==0.13.5`.

**Comment by holtgrewe** [comment]
OK, `v0.13.16` should fix that.
