### ISSUE TITLE
Unable to install in Python 3.12

### ISSUE THREAD

**Issue by jsstevenson** [bihealth/vcfpy#158]
* vcfpy version: 0.13.6 (latest)
* Python version: 3.12
* Operating System: MacOS 13.6

### Description

I'm unable to install on a new 3.12 environment. The Pip error message refers to a module attribute, `SafeConfigParser`, that has been [deprecated](https://docs.python.org/3.12/whatsnew/3.12.html#configparser) in 3.12. At a glance, it appears to be rooted in the Versioneer build management tool that you're using here, but [they claim to have fixed this](https://github.com/python-versioneer/python-versioneer/pull/376).

I know that you don't claim to support 3.12 in the `setup.py` file but I figured I'd flag it for you anyway in case it's an easy fix.

### What I Did

```
[⚙ venv]~/code/retraction % pip install vcfpy     
Collecting vcfpy
  Using cached vcfpy-0.13.6.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /private/var/folders/wx/h1q5fy057t97w4md21k1ktjnlp06wn/T/pip-install-xqxoql9o/vcfpy_a939bfba6aed45e0910fdbaf1c40343f/versioneer.py:432: SyntaxWarning: invalid escape sequence '\s'
        ] = '''
      Traceback (most recent call last):
        File "/Users/jss009/code/retraction/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/jss009/code/retraction/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jss009/code/retraction/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wx/h1q5fy057t97w4md21k1ktjnlp06wn/T/pip-build-env-gn2x9bq0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wx/h1q5fy057t97w4md21k1ktjnlp06wn/T/pip-build-env-gn2x9bq0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/wx/h1q5fy057t97w4md21k1ktjnlp06wn/T/pip-build-env-gn2x9bq0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/wx/h1q5fy057t97w4md21k1ktjnlp06wn/T/pip-build-env-gn2x9bq0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 48, in <module>
        File "/private/var/folders/wx/h1q5fy057t97w4md21k1ktjnlp06wn/T/pip-install-xqxoql9o/vcfpy_a939bfba6aed45e0910fdbaf1c40343f/versioneer.py", line 1505, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/wx/h1q5fy057t97w4md21k1ktjnlp06wn/T/pip-install-xqxoql9o/vcfpy_a939bfba6aed45e0910fdbaf1c40343f/versioneer.py", line 1434, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wx/h1q5fy057t97w4md21k1ktjnlp06wn/T/pip-install-xqxoql9o/vcfpy_a939bfba6aed45e0910fdbaf1c40343f/versioneer.py", line 346, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Separately, I tried in a fresh 3.11 environment and it worked.

**Comment by jsstevenson** [comment]
Looks like this was fixed in https://github.com/bihealth/vcfpy/pull/160. Thanks, @holtgrewe !
